java_test(
    name = "db_test",
    size = "small",
    srcs = ["DbTest.java"],
    test_class = "com.haowei.guice.mysql.DbTest",
    deps = [
        "//src/main/java/com/haowei/guice/mysql:dbmodule",
        "//src/main/java/com/haowei/guice/mysql:user",
        "//src/main/java/com/haowei/guice/mysql:user_service",
        "//:java_test_deps",
    ]
)
